# EDA - NPS Preditivo

Este notebook tem como objetivo realizar uma análise exploratória dos dados de e-commerce para identificar fatores que influenciam a satisfação do cliente (NPS).

A análise irá explorar dados de pedidos, logística, atendimento e perfil de clientes, buscando padrões que expliquem variações no NPS.

## Bibliotecas

Iniciamos o notebook importando as bibliotecas que iremos utilizar na analise.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Importar Dados

Importamos os dados, de formato csv para nosso notebook como um DataFrame.

In [9]:
df = pd.read_csv("../data/desafio_nps_fase_1.csv")

## Análise Inicial e Estatística Básica

Utilizamos os métodos head(), info() e describe() para obter as primeiras informações sobre nossa base de dados.

Também utilizamos o isnull() para buscar valores nulos.

A partir dessas funções iniciais, obtemos uma visão geral e já respondemos algumas perguntas importantes:

- Como nossos dados estão estruturados
- Quais são as colunas que existem
- Quantos registros ele contém
- Quais são os tipos de dados
- Estatísticas descritivaas básicas
- Presença de valores nulos

In [10]:
df.head()

,customer_id,customer_age,customer_region,customer_tenure_months,order_id,order_value,items_quantity,discount_value,payment_installments,delivery_time_days,delivery_delay_days,freight_value,delivery_attempts,customer_service_contacts,resolution_time_days,nps_score,repeat_purchase_30d,complaints_count,csat_internal_score
0,1,63,Nordeste,14,50001,139.73,4,39.35,4,2,2,55.53,3,0,4,6.9,0,3,6.5
1,2,20,Sul,1,50002,458.95,2,9.51,10,6,4,28.23,3,0,10,2.4,0,3,0.0
2,3,46,Nordeste,111,50003,507.06,5,42.82,6,6,1,40.99,1,4,5,4.8,0,7,1.5
3,4,52,Centro-Oeste,117,50004,302.19,2,19.58,9,5,2,35.24,3,1,11,5.9,0,4,0.3
4,5,56,Norte,50,50005,253.06,1,29.37,11,13,1,39.32,1,1,0,6.1,0,3,7.9

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                2500 non-null   int64
 1   customer_age               2500 non-null   int64
 2   customer_region            2500 non-null   str
 3   customer_tenure_months     2500 non-null   int64
 4   order_id                   2500 non-null   int64
 5   order_value                2500 non-null   float64
 6   items_quantity             2500 non-null   int64
 7   discount_value             2500 non-null   float64
 8   payment_installments       2500 non-null   int64
 9   delivery_time_days         2500 non-null   int64
 10  delivery_delay_days        2500 non-null   int64
 11  freight_value              2500 non-null   float64
 12  delivery_attempts          2500 non-null   int64
 13  customer_service_contacts  2500 non-null   int64
 14  resolution_time_days       2500 non-null   int64
 15  nps_score                  2500 non-null   float64
 16  repeat_purchase_30d        2500 non-null   int64
 17  complaints_count           2500 non-null   int64
 18  csat_internal_score        2500 non-null   float64
dtypes: float64(5), int64(13), str(1)
memory usage: 371.2 KB

In [12]:
df.describe()

,customer_id,customer_age,customer_tenure_months,order_id,order_value,items_quantity,discount_value,payment_installments,delivery_time_days,delivery_delay_days,freight_value,delivery_attempts,customer_service_contacts,resolution_time_days,nps_score,repeat_purchase_30d,complaints_count,csat_internal_score
count,2500.00000,2500.000000,2500.000000,2500.00000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000
mean,1250.50000,43.396000,61.322400,51250.50000,434.259740,3.470800,29.745620,6.004000,8.022000,2.187200,38.217016,2.005600,1.519600,5.485600,4.378600,0.087200,4.150400,2.941600
std,721.83216,14.888487,34.478729,721.83216,289.772497,1.687331,29.225603,3.159743,3.770411,1.454442,12.076074,0.815497,1.231512,3.458002,2.510229,0.282184,1.784223,2.378957
min,1.00000,18.000000,1.000000,50001.00000,7.760000,1.000000,0.020000,1.000000,2.000000,0.000000,2.620000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,625.75000,31.000000,31.000000,50625.75000,220.245000,2.000000,8.885000,3.000000,5.000000,1.000000,29.927500,1.000000,1.000000,2.000000,2.600000,0.000000,3.000000,0.700000
50%,1250.50000,43.000000,62.000000,51250.50000,375.515000,3.000000,20.935000,6.000000,8.000000,2.000000,38.500000,2.000000,1.000000,6.000000,4.400000,0.000000,4.000000,2.800000
75%,1875.25000,56.000000,91.000000,51875.25000,577.290000,5.000000,40.832500,9.000000,11.000000,3.000000,46.270000,3.000000,2.000000,8.000000,6.100000,0.000000,5.000000,4.800000
max,2500.00000,69.000000,119.000000,52500.00000,1983.810000,6.000000,230.330000,11.000000,14.000000,8.000000,76.130000,3.000000,7.000000,11.000000,10.000000,1.000000,11.000000,10.000000

In [ ]:
df.isnull().sum()

customer_id                  0
customer_age                 0
customer_region              0
customer_tenure_months       0
order_id                     0
order_value                  0
items_quantity               0
discount_value               0
payment_installments         0
delivery_time_days           0
delivery_delay_days          0
freight_value                0
delivery_attempts            0
customer_service_contacts    0
resolution_time_days         0
nps_score                    0
repeat_purchase_30d          0
complaints_count             0
csat_internal_score          0
dtype: int64